### ISSUE TITLE
Incremental builds

### ISSUE THREAD

**Issue by pungggi** [fiatjaf/react-site#1]
hello, does Sitio, support incremental builds?

IF if would have 10 000 pages for a website and I add 1.
Do I need do rebuild all pages or just one or a few ones?

**Comment by fiatjaf** [comment]
It doesn't, but it should, right? How do you think this could be done?

**Comment by pungggi** [comment]
Well, I am looking for a static file generator that could build incrementally. 

How this could be done? 

I dont know but maybe this post can give some ideas 
https://medium.com/@kenneth_chau/speeding-up-webpack-typescript-incremental-builds-by-7x-3912ba4c1d15
https://fuse-box.org/

**Comment by pungggi** [comment]
This is also inspiring> https://reach.tech/router/large-scale

https://github.com/trivago/parallel-webpack

https://maketips.net/tip/472/rebuild-webpack-bundle-only-if-sources-were-changed

**Comment by fiatjaf** [comment]
Wait, Sitio uses Browserify, not Webpack. We're proudly webpack-free here.
